server:
  id: dev
  file_path_template: tmp/files/:date/:id:ext

session:
  access_token_exp: 900 # 15 min
  refresh_token_exp: 12969000 # 15 day
  access_token_refresh_threshold: 300 #  5 min

github:
  oauth_authorize_url: https://github.com/login/oauth/authorize
  oauth_redirect_uri: http://localhost:3000
  oauth_access_token_uri: https://github.com/login/oauth/access_token
  oauth_state_exp: 600 # 10min
